# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GameMap
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  target 'GameMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
